"use client";

// React


// Flowbite


// Components
import CovertComp from "./components/CovertComp";

export const metadata = {
   title: "Jason",
   description: "Generated by create next app",
};

export default function Home() {
   return (
      <>
         <CovertComp />
      </>
   );
}
