"use client";


// Flowbite
import { Alert } from "flowbite-react";



export const metadata = {
   title: "Jason",
   description: "Generated by create next app",
};

export default function Home() {
   return (
      <main>
         <Alert color="info">Alert!</Alert>
      </main>
   );
}
